#!/usr/bin/env bash
# update-index.sh — regenerate work/README.md, the task index keyed by Jira key.
# Called automatically by new-task.sh and save-progress.sh — never edit the index
# by hand. Reads each work/<KEY>/delivery-state.md for title/status/phase.
# Must stay bash-3.2 compatible.

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$ROOT/work"
[ -d "$WORK" ] || exit 0
OUT="$WORK/README.md"

# Extract "- `field`: value" from delivery-state.md; placeholders (<...>) count as empty.
ds_field() { # ds_field <file> <field>
  V="$(sed -n "s/^- \`$2\`: *//p" "$1" 2>/dev/null | head -1 | tr -d '\`' | sed 's/^ *//;s/ *$//')"
  case "$V" in "<"*|"") echo "" ;; *) echo "$V" ;; esac
}

{
  echo "# work/ — task workspaces, indexed by Jira key"
  echo ""
  echo "One folder per Jira task; the folder name IS the ticket key. Open the key's"
  echo "\`delivery-state.md\` to see where the task stands, and resume it anytime with"
  echo "\`/implement <KEY>\`. Auto-generated by \`tools/update-index.sh\` — do not edit by hand."
  echo ""
  echo "| Jira key | Title | Status | Phase | Last saved |"
  echo "|---|---|---|---|---|"
  for D in "$WORK"/*/; do
    [ -d "$D" ] || continue
    KEY="$(basename "$D")"
    DS="$D/delivery-state.md"
    TITLE=""; STATUS=""; PHASE=""
    if [ -f "$DS" ]; then
      TITLE="$(head -1 "$DS" | sed 's/^# Delivery state: *[A-Za-z0-9-]* *[—-]* *//;s/<ticket title>//')"
      STATUS="$(ds_field "$DS" overall_status)"
      PHASE="$(ds_field "$DS" current_phase)"
    fi
    DATE="$(git -C "$ROOT" log -1 --format=%ad --date=short -- "work/$KEY" 2>/dev/null || true)"
    printf '| [%s](%s/) | %s | %s | %s | %s |\n' \
      "$KEY" "$KEY" "${TITLE:-—}" "${STATUS:-—}" "${PHASE:-—}" "${DATE:-not saved yet}"
  done
} > "$OUT"
echo "✔ work/README.md (task index) regenerated"
